version: 2.1

jobs:
  Copy:
    docker:
      - image: cimg/base:latest
        auth:
          user: $SERVER_USERNAME
          host: $SERVER_HOST
          port: $SERVER_PORT
          key: $SERVER_PRIVATE_KEY
          script: |
            cd /var/www/circlecitest
            cp adas.txt test.txt
    # steps:
    #   - ssh/with-known-hosts:
    #       user: $SERVER_USERNAME
    #       host: $SERVER_HOST
    #       port: $SERVER_PORT
    #       key: $SERVER_PRIVATE_KEY
    #       script: |
    #         cd /var/www/circlecitest
    #         cp adas.txt test.txt

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # - build
      - Copy:
          filters:
            branches:
              only:
                - development